//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFarmBA_WFA.ModelContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppUser()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public System.Guid ActivationCode { get; set; }
        public bool Active { get; set; }
        public string Email { get; set; }
        public int URole { get; set; }
        public Nullable<System.DateTime> Veri_Yaratma_Tarihi { get; set; }
        public Nullable<System.DateTime> Veri_Güncelleme_Tarihi { get; set; }
        public Nullable<System.DateTime> Veri_Silme_Tarihi { get; set; }
        public int Veri_Durumu { get; set; }
        public bool RememberMe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
