//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFarmBA_WFA.ModelContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StorageOrder()
        {
            this.StorageOrderDetails = new HashSet<StorageOrderDetail>();
        }
    
        public int ID { get; set; }
        public string ShippedAddress { get; set; }
        public string ShippedCity { get; set; }
        public string ShippedCountry { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int Status { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Shipper Shipper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageOrderDetail> StorageOrderDetails { get; set; }
    }
}
